version: '3.9'

services:
  app:
    image: python:3.10.13-alpine
    ports:
      - "9099:8099"
    volumes:
      - type: bind
        source: .
        target: /app
    restart: unless-stopped
    command: sh -c " pip install -r /app/requirements.txt && \
      python3 /app/main.py"
