version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: python:3.10.13-alpine
    ports:
      - "9099:8099"
    volumes:
      - type: bind
        source: .
        target: /app
    restart: unless-stopped
